linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - gci
    - gofumpt
    - goimports
    - exhaustivestruct
    - nonamedreturns
    - exhaustruct
    - maligned
    - funlen
    - lll
    - durationcheck
    - gomnd
    - ireturn
    - nosprintfhostport
    - varnamelen
    - cyclop
    - goerr113
    - wrapcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
    - ifshort
    - interfacer
    - varcheck
    - deadcode
    - nosnakecase
    - scopelint
    - golint
    - nilerr
    - tagalign
    - gomoddirectives
    - dupword
    - tagliatelle